name: CI

on:
  push:
    branches:
      - main
      - lab3

    tags:
      - '*'

  pull_request:
    branches:
      - main
    tags:
      - '*'

  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run flake8
        run: |
          PYTHONPATH=. flake8 app.py migrate.py tests

      - name: Run tests with coverage
        run: |
          PYTHONPATH=. pytest \
            --cov=app \
            --cov-report=xml \
            --cov-report=term-missing \
            --cov-fail-under=40

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
