name: Deploy to Target VM

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare deployment files on target
        run: |
          ssh -i ~/.ssh/id_ed25519 student@192.168.64.13 "mkdir -p /opt/mywebapp"
          scp -i ~/.ssh/id_ed25519 mywebapp/deploy/deploy-container.sh student@192.168.64.13:/opt/mywebapp/
          scp -i ~/.ssh/id_ed25519 mywebapp/deploy/verify.sh student@192.168.64.13:/opt/mywebapp/
          scp -i ~/.ssh/id_ed25519 mywebapp/deploy/mywebapp-container.service student@192.168.64.13:/opt/mywebapp/

      - name: Deploy container on target
        run: |
          IMAGE="ghcr.io/valmai12/devops-labs/mywebapp:stable"
          ssh -i ~/.ssh/id_ed25519 student@192.168.64.13 "chmod +x /opt/mywebapp/deploy-container.sh /opt/mywebapp/verify.sh && /opt/mywebapp/deploy-container.sh $IMAGE"

      - name: Verify deployment
        run: |
          ssh -i ~/.ssh/id_ed25519 student@192.168.64.13 "/opt/mywebapp/verify.sh"